version: '3.8'

services:
  mongo:
    image: mongo:4.2
    container_name: mongodb-ark
    ports:
      - '27019:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
